[[pages]]
path = "pages/notes.py"
name = "Take Notes"
icon = "ğŸ“"
url_path = "notes"

[[pages]]
path = "pages/explorer.py"
name = "Explorer"
icon = "ğŸ“‚"
url_path = "explorer"

[[pages]]
path = "pages/settings.py"
name = "Settings"
icon = "âš™ï¸"
url_path = "settings"

